INSERT INTO Profiles VALUES (1, 'Computer Science', 101, 1);
INSERT INTO Profiles VALUES (2, 'Biology', 101, 1);
INSERT INTO Profiles VALUES (3, 'History', 101, 1);
INSERT INTO Profiles VALUES (1, 'Computer Science', 101, 2);
INSERT INTO Profiles VALUES (2, 'Biology', 101, 2);
INSERT INTO Profiles VALUES (3, 'History', 101, 2);
INSERT INTO Profiles VALUES (1, 'Computer Science', 101, 3);
INSERT INTO Profiles VALUES (2, 'Biology', 101, 3);
INSERT INTO Profiles VALUES (3, 'History', 101, 3);
INSERT INTO Profiles VALUES (1, 'Computer Science', 101, 4);
INSERT INTO Profiles VALUES (2, 'Biology', 101, 4);
INSERT INTO Profiles VALUES (3, 'History', 101, 4);
INSERT INTO Profiles VALUES (1, 'Computer Science', 102, 1);
INSERT INTO Profiles VALUES (2, 'Biology', 102, 1);
INSERT INTO Profiles VALUES (3, 'History', 102, 1);
INSERT INTO Profiles VALUES (1, 'Computer Science', 102, 2);
INSERT INTO Profiles VALUES (2, 'Biology', 102, 2);
INSERT INTO Profiles VALUES (3, 'History', 102, 2);
INSERT INTO Profiles VALUES (1, 'Computer Science', 102, 3);
INSERT INTO Profiles VALUES (2, 'Biology', 102, 3);
INSERT INTO Profiles VALUES (3, 'History', 102, 3);
INSERT INTO Profiles VALUES (1, 'Computer Science', 102, 4);
INSERT INTO Profiles VALUES (2, 'Biology', 102, 4);
INSERT INTO Profiles VALUES (3, 'History', 102, 4);
INSERT INTO Profiles VALUES (1, 'Computer Science', 103, 1);
INSERT INTO Profiles VALUES (2, 'Biology', 103, 1);
INSERT INTO Profiles VALUES (3, 'History', 103, 1);
INSERT INTO Profiles VALUES (1, 'Computer Science', 103, 2);
INSERT INTO Profiles VALUES (2, 'Biology', 103, 2);
INSERT INTO Profiles VALUES (3, 'History', 103, 2);
INSERT INTO Profiles VALUES (1, 'Computer Science', 103, 3);
INSERT INTO Profiles VALUES (2, 'Biology', 103, 3);
INSERT INTO Profiles VALUES (3, 'History', 103, 3);
INSERT INTO Profiles VALUES (1, 'Computer Science', 103, 4);
INSERT INTO Profiles VALUES (2, 'Biology', 103, 4);
INSERT INTO Profiles VALUES (3, 'History', 103, 4);